### ISSUE TITLE
Fehler(82,12): PLS-00201: ID 'CHAR_TABLE' muss deklariert werden

### ISSUE THREAD

**Issue by kbitzi** [j-sieben/Benutzerverwaltung#1]
Guten Tag,

habe versucht die Applikation zu installieren. Erhalte diesen Fehler in folgenden Packages:
BL_RECHT_PKG und BV_UTILS. 

Was mache ich falsch? 

Freundliche Grüsse
Kurt

**Comment by j-sieben** [comment]
Hallo,

ich überarbeite gerade die Anwendung, das kann aber, muss ich gestehen, noch ein wenig dauern. Der aktuelle Fehler komm dadurch zustande, dass ein Datentyp CHAR_TABLE fehlt oder Ausführungsrechte darauf nicht vorhanden sind.

Falls der Typ fehlt, muss er angelegt werden wie folgt:

create type char_table as table of varchar2(4000 byte);

Falls der Typ in einem Utility-Benutzer vorhanden ist, muss ein execute-Recht darauf eingerichtet werden.

Ich bin aber nicht sicher, ob die Anwendung anschließend komplett funktioniert, ich stelle sie gerade auf eine neuere APEX-Version um.

Beste Grüße

Jürgen

**Comment by kbitzi** [comment]
Hallo Jürgen,

vielen Dank. Hat bestens funktioniert. Create Type hat gefehlt. Habe das install-script entsprechend angepasst. Nun funktioniert das Einspielen einwandfrei. Werde die Applikation nun testen. 

Gruss
Kurt

**Comment by j-sieben** [comment]
OK,
aber bitte investieren Sie nicht zuviel Zeit, falls es nicht funktioniert wie gewünscht. Wie gesagt, ist da im Moment einiges im Umbau.

Beste Grüße,

Jürgen
